### PR TITLE
add new game

### PR DESCRIPTION
**Pull request by Rahib777-7**

### CODE REVIEW

**Comment by nate-games** [comment]
Hey there,I haven't reviewed this yet but I will eventually when I have the time. Thanks though it's cool to know that you are the same person who worked on 3kh0!

**Comment by nate-games** [comment]
I just reviewed its great but it looks like you forgot something...

The favicon and <title> are both among us and there are no bugs so the .fullscreen-text (DIV) isn't needed.

**Comment by nate-games** [comment]
### Hey,
@Rahib777-7  Pull Request #33

Sorry but, I don't think this is a good idea... it could offend some people (not me) but it is risky and I don't want the site getting taken down.

**Comment by Rahib777-7** [comment]
> ### Hey,
> 
> @Rahib777-7 Pull Request #33
> 
> Sorry but, I don't think this is a good idea... it could offend some people (not me) but it is risky and I don't want the site getting taken down.

ill edit a  bit so it isnt as "offensive"

**Comment by nate-games** [comment]
I'll add a popup to let users know.

**Comment by nate-games** [comment]
I am not risking getting banned.

**Pull request closed without merging**
